import twin4build as tb
import datetime
import twin4build.examples.utils as utils
import torch.nn as nn
import torch
import json
from dateutil.tz import gettz 
import twin4build.utils.plot.plot as plot
import twin4build.utils.input_output_types as tps
import unittest
import gymnasium as gym
import numpy as np
from datetime import timezone, timedelta
import sys
import os
import logging

# Configure logging to write to a file
log_file = os.path.join(os.path.dirname(__file__), 'simulation_tests.log')
logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(log_file),
        #logging.StreamHandler()  # Keep console output as well
    ]
)

uppath = lambda _path, n: os.sep.join(_path.split(os.sep)[:-n])
file_path = os.path.join(uppath(os.path.abspath(__file__), 3), "t4b_gym")
sys.path.append(file_path)
from t4b_gym_env import t4b_gym_env, gym_simulator
from tqdm import tqdm

def fcn(self):
    ##############################################################
    ################## First, define components ##################
    ##############################################################
    occupancy_schedule = tb.ScheduleSystem(
        weekDayRulesetDict={
            "ruleset_default_value": 0,
            "ruleset_start_minute": [0, 0, 0, 0, 0, 0, 0],
            "ruleset_end_minute": [0, 0, 0, 0, 0, 0, 0],
            "ruleset_start_hour": [6, 7, 8, 12, 14, 16, 18],
            "ruleset_end_hour": [7, 8, 12, 14, 16, 18, 22],
            "ruleset_value": [3, 5, 20, 25, 27, 7, 3]},
        add_noise=True,
        saveSimulationResult=True,
        id="Occupancy schedule")
    
    co2_setpoint_schedule = tb.ScheduleSystem(
        weekDayRulesetDict={
            "ruleset_default_value": 900,
            "ruleset_start_minute": [],
            "ruleset_end_minute": [],
            "ruleset_start_hour": [],
            "ruleset_end_hour": [],
            "ruleset_value": []},
        saveSimulationResult=True,
        id="CO2 setpoint schedule")

    co2_controller = tb.PIDControllerSystem(
        K_p=-0.001,
        K_i=-0.001,
        K_d=0,
        saveSimulationResult=True,
        id="CO2 controller")

    supply_damper = tb.DamperSystem(
        nominalAirFlowRate=tb.PropertyValue(hasValue=1.6),
        a=5,
        saveSimulationResult=True,
        id="Supply damper")

    return_damper = tb.DamperSystem(
        nominalAirFlowRate=tb.PropertyValue(hasValue=1.6),
        a=5,
        saveSimulationResult=True,
        id="Return damper")

    space = tb.BuildingSpaceCo2System(
        airVolume=466.54,
        outdoorCo2Concentration=500,
        infiltration=0.005,
        generationCo2Concentration=0.0042*1000*1.225,
        saveSimulationResult=True,
        id="Space")

    #################################################################
    ################## Add connections to the model #################
    #################################################################
    self.add_connection(co2_controller, supply_damper,
                         "inputSignal", "damperPosition")
    self.add_connection(co2_controller, return_damper,
                         "inputSignal", "damperPosition")
    self.add_connection(supply_damper, space,
                         "airFlowRate", "supplyAirFlowRate")
    self.add_connection(return_damper, space,
                         "airFlowRate", "returnAirFlowRate")
    self.add_connection(occupancy_schedule, space,
                         "scheduleValue", "numberOfPeople")
    self.add_connection(space, co2_controller,
                         "indoorCo2Concentration", "actualValue")
    self.add_connection(co2_setpoint_schedule, co2_controller,
                         "scheduleValue", "setpointValue")
    
def load_test_model():
    model = tb.Model(id="simple_co2_control")
    model.load(fcn=fcn, verbose=False)
    return model


class TestCustomGymSimulator(unittest.TestCase):
    def setUp(self):
        self.model = load_test_model()
        self.simulator = gym_simulator(self.model, enable_logging=True)
        self.stepSize = 600 #Seconds
        self.start_time = datetime.datetime(year=2024, month=1, day=10, hour=0, minute=0, second=0, tzinfo=gettz("Europe/Copenhagen"))
        self.end_time = datetime.datetime(year=2024, month=1, day=12, hour=0, minute=0, second=0, tzinfo=gettz("Europe/Copenhagen"))

        self.simulator.initialize_simulation(self.start_time, self.end_time, self.stepSize)
        self.show_progress_bar = True


    def test_non_controlled_simulation(self):
        """Test that the simulation runs without any control actions"""
        #SecondTime is the timesteps in seconds, dateTime is the timesteps in datetime
        #They are generated by the initialize_simulation method
        if self.show_progress_bar:
            for self.secondTime, self.dateTime in tqdm(zip(self.simulator.secondTimeSteps,self.simulator.dateTimeSteps), total=len(self.simulator.dateTimeSteps)):
                self.simulator.step_simulation()
        else:
            for self.secondTime, self.dateTime in zip(self.simulator.secondTimeSteps,self.simulator.dateTimeSteps):
                self.simulator.step_simulation()
        #Check that the current_step is correct
        self.assertEqual(self.simulator.current_step, len(self.simulator.dateTimeSteps))

    def test_controlled_simulation(self):
        """Test that the simulation runs with control actions"""
        #Create a controlled simulation
        self.simulator.add_control_input("Supply damper", "damperPosition")
        self.simulator.add_control_input("Return damper", "damperPosition")
        self.simulator.add_observation_output("CO2 setpoint schedule", "scheduleValue")
        self.simulator.add_observation_output("Space", "indoorCo2Concentration")
        
        def control_action_function(observation):
            #Get the setpoint value
            setpoint_value = observation["CO2 setpoint schedule"]["scheduleValue"]
            #Get the actual value
            actual_value = observation["Space"]["indoorCo2Concentration"]
            #Calculate the error
            error = setpoint_value - actual_value
            #Calculate the control action with a simple P controller
            control_action = error * 0.001
            #Return the control action with the correct format
            return {"Supply damper": {"damperPosition": control_action}, "Return damper": {"damperPosition": control_action}}

        #Run the simulation
        if self.show_progress_bar:
            for self.secondTime, self.dateTime in tqdm(zip(self.simulator.secondTimeSteps,self.simulator.dateTimeSteps), total=len(self.simulator.dateTimeSteps)):
                control_action = control_action_function(self.simulator.get_observations())
                self.simulator.step_simulation(control_action)
        else:
            for self.secondTime, self.dateTime in zip(self.simulator.secondTimeSteps,self.simulator.dateTimeSteps):
                control_action = control_action_function(self.simulator.get_observations())
                self.simulator.step_simulation(control_action)
        
        #Check that the current_step is correct
        self.assertEqual(self.simulator.current_step, len(self.simulator.dateTimeSteps))

class TestT4BGymEnv(unittest.TestCase):
    def setUp(self):
        # Load any T4B model for testing
        self.model = load_test_model()  # You define this based on your needs
        # Create environment
        self.env = t4b_gym_env(
            model=self.model,
            io_config_file='t4b_gym/testing/policy_input_output.json',
        )
        #TODO: At some point, the simulation time should be defined during training of the RL agent
        self.stepSize = 600 #Seconds
        self.start_time = datetime.datetime(year=2024, month=1, day=10, hour=0, minute=0, second=0, tzinfo=gettz("Europe/Copenhagen"))
        self.end_time = datetime.datetime(year=2024, month=1, day=12, hour=0, minute=0, second=0, tzinfo=gettz("Europe/Copenhagen"))

        self.env.simulator.initialize_simulation(self.start_time, self.end_time, self.stepSize)
        self.show_progress_bar = True

    def test_space_creation(self):
        """Test if observation and action spaces are created correctly"""
        # Check observation space matches input config
        for comp_id, config in self.io_config['input'].items():
            self.assertIn(comp_id, self.env.observation_space.spaces)
            space = self.env.observation_space.spaces[comp_id]
            self.assertEqual(space.low[0], config['min'])
            self.assertEqual(space.high[0], config['max'])

        # Check action space matches output config
        for comp_id, config in self.io_config['output'].items():
            self.assertIn(comp_id, self.env.action_space.spaces)
            space = self.env.action_space.spaces[comp_id]
            self.assertEqual(space.low[0], config['min'])
            self.assertEqual(space.high[0], config['max'])

    def test_reset(self):
        """Test environment reset functionality"""
        obs, info = self.env.reset()
        
        # Check observation structure
        self.assertEqual(set(obs.keys()), set(self.io_config['input'].keys()))
        
        # Check observation values are within bounds
        for comp_id, value in obs.items():
            config = self.io_config['input'][comp_id]
            self.assertTrue(np.all(value >= config['min']))
            self.assertTrue(np.all(value <= config['max']))

    def test_step(self):
        """Test environment step functionality"""
        obs, _ = self.env.reset()
        
        # Create valid action
        action = {
            comp_id: np.array([
                (config['max'] + config['min']) / 2  # middle of range
            ])
            for comp_id, config in self.io_config['output'].items()
        }
        
        # Take step
        next_obs, reward, terminated, truncated, info = self.env.step(action)
        
        # Check observation structure maintained
        self.assertEqual(set(next_obs.keys()), set(self.io_config['input'].keys()))
        
        # Check values within bounds
        for comp_id, value in next_obs.items():
            config = self.io_config['input'][comp_id]
            self.assertTrue(np.all(value >= config['min']))
            self.assertTrue(np.all(value <= config['max']))
        
        # Check reward is finite
        self.assertTrue(np.isfinite(reward))

    def test_time_progression(self):
        """Test that simulation time progresses correctly"""
        initial_time = self.env.simulator.dateTime
        
        # Take multiple steps
        for _ in range(5):
            action = self.get_dummy_action()
            _, _, _, _, _ = self.env.step(action)
        
        # Check time advanced correctly
        expected_time = initial_time + timedelta(seconds=5 * self.env.simulator.stepSize)
        self.assertEqual(self.env.simulator.dateTime, expected_time)

    def test_simulation_bounds(self):
        """Test simulation respects time bounds"""
        # Run until end
        done = False
        while not done:
            action = self.get_dummy_action()
            _, _, terminated, truncated, _ = self.env.step(action)
            done = terminated or truncated
        
        # Check we didn't exceed endTime
        self.assertLessEqual(self.env.simulator.dateTime, self.env.simulator.endTime)

    def test_invalid_actions(self):
        """Test environment handles invalid actions appropriately"""
        self.env.reset()
        
        # Test action too high
        action = {
            comp_id: np.array([config['max'] * 2])
            for comp_id, config in self.io_config['output'].items()
        }
        next_obs, _, _, _, _ = self.env.step(action)
        # Should still get valid observations
        self.check_observations_valid(next_obs)

        # Test action too low
        action = {
            comp_id: np.array([config['min'] - 1])
            for comp_id, config in self.io_config['output'].items()
        }
        next_obs, _, _, _, _ = self.env.step(action)
        self.check_observations_valid(next_obs)

    def test_component_failure(self):
        """Test environment handles component failures gracefully"""
        self.env.reset()
        
        # Simulate component failure by setting invalid values
        for component in self.env.simulator.model.components.values():
            if hasattr(component, 'output'):
                for output in component.output.values():
                    output.set(float('nan'))
        
        # Environment should still function
        action = self.get_dummy_action()
        try:
            next_obs, _, _, _, _ = self.env.step(action)
            self.check_observations_valid(next_obs)
        except Exception as e:
            self.fail(f"Environment failed to handle component failure: {e}")

    def test_step_timing(self):
        """Test environment step execution time"""
        import time
        
        self.env.reset()
        action = self.get_dummy_action()
        
        # Measure average step time
        n_steps = 100
        start_time = time.time()
        
        for _ in range(n_steps):
            self.env.step(action)
        
        avg_step_time = (time.time() - start_time) / n_steps
        
        # Assert reasonable performance (adjust threshold as needed)
        self.assertLess(avg_step_time, 0.1)  # 100ms per step

    def test_memory_usage(self):
        """Test environment memory usage"""
        import psutil
        import os
        
        process = psutil.Process(os.getpid())
        initial_memory = process.memory_info().rss
        
        # Run many steps
        self.env.reset()
        for _ in range(1000):
            self.env.step(self.get_dummy_action())
        
        final_memory = process.memory_info().rss
        memory_increase = final_memory - initial_memory
        
        # Check memory growth is reasonable
        self.assertLess(memory_increase / 1024 / 1024, 100)  # Less than 100MB growth

    def get_dummy_action(self):
        """Create a valid dummy action"""
        return {
            comp_id: np.array([(config['max'] + config['min']) / 2])
            for comp_id, config in self.io_config['output'].items()
        }

    def check_observations_valid(self, obs):
        """Check if observations are valid"""
        for comp_id, value in obs.items():
            config = self.io_config['input'][comp_id]
            self.assertTrue(np.all(np.isfinite(value)))
            self.assertTrue(np.all(value >= config['min']))
            self.assertTrue(np.all(value <= config['max']))


if __name__ == "__main__":
    unittest.main()

    """
    # Create an instance of the test class and run the specific test
    test_case = TestCustomGymSimulator()
    test_case.setUp()
    #test_case.test_non_controlled_simulation()
    test_case.test_controlled_simulation()
    """
    
 
